spring:
  application:
    name: wonder-steps-generator
  mongodb:
#    uri: mongodb+srv://${MONGODB_USERNAME}:${MONGODB_PASSWORD}@contentgenerator.uovnyyw.mongodb.net/wondersteps?retryWrites=true&w=majority
    uri: mongodb+srv://bistropediacom_db_user:KomNrNOMiTLYS3Bo@contentgenerator.uovnyyw.mongodb.net/wondersteps?retryWrites=true&w=majority
  data:
    mongodb:
      auto-index-creation: false
  thymeleaf:
    cache: false


wonder-steps-generator:
  mongodb:
    collection: wondersteps
    create-collections: false
    verify-connection: true
  static-site:
    enabled: true
    output-dir: build/static-site
    trip-status: PUBLISHED
    featured-only: true
    lang: en
    base-url:
